-- return {
--   "rose-pine/neovim",
--   name = "rose-pine",
--   config = function()
--     vim.cmd([[colorscheme rose-pine]])
--   end,
-- }
--
-- return {
--   "navarasu/onedark.nvim",
--   name = "onedark",
--   config = function()
--     vim.cmd([[colorscheme onedark]])
--   end,
-- }
--
return {}
